[package]
name = "polonius"
version = "0.3.0"
authors = ["The Rust Project Developers", "Polonius Developers"]
description = "Core definition for the Rust borrow checker"
license = "Apache-2.0/MIT"
repository = "https://github.com/rust-lang-nursery/polonius"
readme = "README.md"
keywords = ["compiler", "borrowck", "datalog"]
edition = "2018"

[dev-dependencies]
assert_cli = "0.6"
diff = "0.1.0"

[dependencies]
log = "0.4"
env_logger = "0.5"
datafrog = "2.0.0"
failure = "0.1.1"
rustc-hash = "1.0.0"
structopt = "0.2.8"
clap = "2.31.2"
polonius-engine = {version = "0.6.2", path = "polonius-engine" }
polonius-parser = {version = "0.3.0", path = "polonius-parser" }

[workspace]
